table 'Adapted Screenplay'
	lineageTag: 6b375445-2d2d-4e2e-af73-8381136a690f

	column Name
		dataType: string
		lineageTag: 5f576b85-0232-40e4-8094-04223b6c530d
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 34d7be0e-ddc8-4503-b6ff-fc2a92617d8e
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Race
		dataType: string
		lineageTag: 20de24b9-a6c2-4147-b574-c156d65aae6a
		summarizeBy: none
		sourceColumn: Race

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 8b437a6c-c347-40c9-9721-dd4ddf03a8b9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: eb1812e1-003a-460b-bb7b-aee4abe73f2c
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 9f9b3bb8-908c-4b1e-b4d6-110b168095bf
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column 'No. of Best Adapted Screenplay Wins'
		dataType: int64
		formatString: 0
		lineageTag: 5f5a29b9-41be-4122-999a-796296426877
		summarizeBy: sum
		sourceColumn: No. of Best Adapted Screenplay Wins

		annotation SummarizationSetBy = Automatic

	partition 'Adapted Screenplay' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\Data Analyst Projects\Oscars Awards Analysis\Collected Datasets\Adapted Screenplay.xlsx"), null, true),
				    #"Give me 10 pieces of data in Ex_Sheet" = Source{[Item="Give me 10 pieces of data in Ex",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Give me 10 pieces of data in Ex_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Name", type text}, {"Country", type text}, {"Race", type text}, {"Status", type text}, {"Gender", type text}, {"Occupation", type text}, {"No. of Best Adapted Screenplay Wins", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

