table 'Box Office Collected'
	lineageTag: 3c30a51b-1823-4914-9f57-ce43bedfef87

	column 'Film Name'
		dataType: string
		lineageTag: 51de6a9e-647b-49ba-8eae-4a9104135bbe
		summarizeBy: none
		sourceColumn: Film Name

		annotation SummarizationSetBy = Automatic

	column 'Release Year'
		dataType: int64
		formatString: 0
		lineageTag: a2855714-79e1-4e2e-b27a-2e106c7afb26
		summarizeBy: sum
		sourceColumn: Release Year

		annotation SummarizationSetBy = Automatic

	column 'Awarded Year'
		dataType: int64
		formatString: 0
		lineageTag: 75b4ed40-4149-493f-8d94-51b5ee7b56c0
		summarizeBy: sum
		sourceColumn: Awarded Year

		annotation SummarizationSetBy = Automatic

	column 'Oscar Nominations'
		dataType: int64
		formatString: 0
		lineageTag: ef7e6b9c-2451-4d65-b356-f76db3154cc5
		summarizeBy: sum
		sourceColumn: Oscar Nominations

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: abaa5f4b-45e2-4609-84b4-dbc9f5620ce4
		summarizeBy: none
		sourceColumn: Director

		annotation SummarizationSetBy = Automatic

	column Producer
		dataType: string
		lineageTag: cf3f7fbb-bc2f-4024-b0c7-104e85c48fdc
		summarizeBy: none
		sourceColumn: Producer

		annotation SummarizationSetBy = Automatic

	column 'Production Company'
		dataType: string
		lineageTag: 820fcbc9-fbee-45ab-a93d-10d282d9562a
		summarizeBy: none
		sourceColumn: Production Company

		annotation SummarizationSetBy = Automatic

	column Distributor
		dataType: string
		lineageTag: 4a71bf4a-8407-49a5-82ab-9f27682e1e8c
		summarizeBy: none
		sourceColumn: Distributor

		annotation SummarizationSetBy = Automatic

	column 'Oscar Wins'
		dataType: int64
		formatString: 0
		lineageTag: 64f2bc99-eb1e-4508-90ea-cdd57306f56b
		summarizeBy: sum
		sourceColumn: Oscar Wins

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: int64
		formatString: 0
		lineageTag: 663f610b-1792-4e92-a700-cd136308c1e9
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

	column 'Box Office'
		dataType: int64
		formatString: 0
		lineageTag: 0dc6379f-8058-4c58-b517-2994110554fe
		summarizeBy: sum
		sourceColumn: Box Office

		annotation SummarizationSetBy = Automatic

	column 'Box Office Adjusted to Inflation'
		dataType: int64
		formatString: 0
		lineageTag: a5ede457-2842-42ec-8bf1-25b8d766a92d
		summarizeBy: sum
		sourceColumn: Box Office Adjusted to Inflation

		annotation SummarizationSetBy = Automatic

	column 'Year Group'
		dataType: string
		lineageTag: 90e3ec87-f404-421a-bda2-891d3f2ec218
		summarizeBy: none
		sourceColumn: Year Group

		annotation SummarizationSetBy = Automatic

	partition 'Box Office Collected' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\Data Analyst Projects\Oscars Awards Analysis\Collected Datasets\Box Office Collected.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Film Name", type text}, {"Release Year", Int64.Type}, {"Awarded Year", Int64.Type}, {"Oscar Nominations", Int64.Type}, {"Director", type text}, {"Producer", type text}, {"Production Company", type text}, {"Distributor", type text}, {"Oscar Wins", Int64.Type}, {"Budget", Int64.Type}, {"Box Office", Int64.Type}, {"Box Office Adjusted to Inflation", Int64.Type}, {"Year Group", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

