table 'Original Screenplay'
	lineageTag: 65fcdd5c-d4c7-44aa-8659-67b4b8b960b5

	column Name
		dataType: string
		lineageTag: ef167146-7119-4252-a039-b10d6468729c
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6bb1357b-a4d9-4600-b37a-ebc85cba1c53
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Race
		dataType: string
		lineageTag: 5eaa53ae-794f-4ad6-902e-88b49dbd45a4
		summarizeBy: none
		sourceColumn: Race

		annotation SummarizationSetBy = Automatic

	column 'Age '
		dataType: int64
		formatString: 0
		lineageTag: 7256b620-7573-4f56-8d2f-2b28f688aebe
		summarizeBy: sum
		sourceColumn: "Age "

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: d42001a0-a0d4-4b56-b4a1-c74e7b66607f
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 7b0b4b35-e453-4729-873c-3471fe1ff7b5
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: 9fe322c2-c6c7-47c9-817e-a1c103878aba
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column 'No. of Best Original Screenplay Wins'
		dataType: int64
		formatString: 0
		lineageTag: f385137c-4ab3-43bc-803f-f988af8d4a3d
		summarizeBy: sum
		sourceColumn: No. of Best Original Screenplay Wins

		annotation SummarizationSetBy = Automatic

	column Year-Group
		dataType: string
		lineageTag: 52125be8-808b-4a59-af02-bb1962705449
		summarizeBy: none
		sourceColumn: Year-Group

		annotation SummarizationSetBy = Automatic

	partition 'Original Screenplay' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\Data Analyst Projects\Oscars Awards Analysis\Collected Datasets\Original Screenplay.xlsx"), null, false),
				    #"Give me 10 pieces of data in Ex_sheet" = Source{[Item="Give me 10 pieces of data in Ex",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Give me 10 pieces of data in Ex_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Bottom Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Name", type text}, {"Country", type text}, {"Race", type text}, {"Age ", Int64.Type}, {"Status", type text}, {"Gender", type text}, {"Occupation", type text}, {"No. of Best Original Screenplay Wins", Int64.Type}, {"Year-Group", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

